# DVC Parameters - references to actual config files
data:
  data_sources:
    movielens:
      dataset_size: "ml-latest-small"

two_tower:
  training:
    learning_rate: 0.001
    num_epochs: 50
  model:
    embedding_dim: 128

bert4rec:
  model:
    hidden_dim: 256
    num_layers: 4
  training:
    learning_rate: 0.0001
    mask_prob: 0.15